# Config with testing path for PMM trajectory generation

waypoints:
  [ 
    [ -8.91373940939495, -12.064213598133927, 0.0],
    [ -16.989356881873896, -12.343490298141937, 0.0],
    [ -14.228245917414611, -4.749422924269266, 0.0],
    [ 0.12019983214080998, 14.999518392280258, 0.0],
    [ 6.489356881873895, 19.972186842198226, 0.0],
    [ 8.719251995549119, 12.205516975454705, 0.0],
    [ 8.719251995549119, -12.205516975454705, 0.0],
    [ 6.489356881873898, -19.972186842198226, 0.0],
    [ 0.12019983214080998, -14.999518392280258, 0.0],
    [ -14.228245917414611, 4.749422924269266, 0.0],
    [ -16.989356881873896, 12.343490298141933, 0.0],
    [ -8.91373940939495, 12.064213598133927, 0.0],
    [ 14.302533499119654, 4.520789257039099, 0.0],
    [ 21.0, 0.0, 0.0],
    [ 14.302533499119654, -4.520789257039099, 0.0],
    [ -8.91373940939495, -12.064213598133927, 0.0],
    [ -16.989356881873896, -12.343490298141937, 0.0],
    [ -14.228245917414611, -4.749422924269266, 0.0],
    [ 0.12019983214080998, 14.999518392280258, 0.0],
    [ 6.489356881873895, 19.972186842198226, 0.0],
  ]
start:
  position: [0, 0, 0]
  velocity: [0, 0, 0]

end:
  position: [8.719251995549119, 12.205516975454705, 0.0]
  velocity: [0, 0, 0]
